"""Generate quiz JSON files for all ML and Programming topics (10 questions each)."""
import json, os
os.makedirs('data/quizzes', exist_ok=True)

def q(question, options, correct, explanation=""):
    return {"question": question, "options": options, "correct": correct, "explanation": explanation}

def save(filename, course_label, title, questions):
    assert len(questions) >= 10, f"{filename}: need 10 questions, got {len(questions)}"
    data = {"course_label": course_label, "title": title, "questions": questions}
    with open(f"data/quizzes/{filename}.json", "w") as f:
        json.dump(data, f, indent=2)
    print(f"  ✅ {filename}.json ({len(questions)} questions)")

# ════════════════════════════════════════════════════════════
# ML QUIZZES
# ════════════════════════════════════════════════════════════

save("ml-linear-regression", "Machine Learning", "Linear Regression", [
    q("Which metric is most interpretable when the target is in dollars?",
      ["R² Score","RMSE","MSE","Adjusted R²"], "b",
      "RMSE is in the same units as the target variable, making it directly interpretable."),
    q("Which regularization method can reduce some feature weights to exactly zero?",
      ["Ridge (L2)","ElasticNet only","Lasso (L1)","OLS"], "c",
      "Lasso (L1) applies absolute-value penalty which can zero out weights entirely — useful for feature selection."),
    q("Before using Ridge regression, you should:",
      ["Scale features with StandardScaler","Encode all features as binary","Remove all null values only","Normalize the target variable"], "a",
      "Ridge is sensitive to feature magnitudes. StandardScaler ensures all features contribute equally to the penalty."),
    q("An R² score of 0.95 means:",
      ["The model is 95% accurate","95% of predictions are correct","RMSE is 5%","The model explains 95% of the variance in the target"], "d",
      "R² measures explained variance, not accuracy. 0.95 means 95% of the target's variability is captured by the model."),
    q("Which is NOT a valid use case for linear regression?",
      ["Predicting house prices","Classifying spam vs. not spam","Forecasting next month's sales","Estimating student exam scores"], "b",
      "Classification requires predicting categories. Linear regression outputs continuous values, not class probabilities."),
    q("What problem does Ridge regression solve that OLS cannot?",
      ["High bias","Multicollinearity between features","Non-linear relationships","Missing data"], "b",
      "Ridge adds an L2 penalty that shrinks correlated feature weights, stabilising estimates when multicollinearity is present."),
    q("The intercept (b) in y = wx + b represents:",
      ["The slope of the line","The target value when all features are zero","The regularisation term","The error term"], "b",
      "The intercept is the predicted value when all input features equal zero."),
    q("Which loss function does Ordinary Least Squares minimise?",
      ["Mean Absolute Error","Mean Squared Error","Log Loss","Hinge Loss"], "b",
      "OLS minimises the sum (and mean) of squared residuals between predicted and actual values."),
    q("A residual plot showing a clear curve pattern suggests:",
      ["The model is well-fitted","Heteroscedasticity","A non-linear relationship not captured by the model","Multicollinearity"], "c",
      "Curved patterns in residuals indicate the linear model is missing non-linear structure in the data."),
    q("ElasticNet combines which two regularisation methods?",
      ["OLS and Ridge","Lasso and Ridge","OLS and Lasso","Ridge and Polynomial"], "b",
      "ElasticNet = alpha * L1 + (1-alpha) * L2, letting you control the mixture."),
])

save("ml-classification", "Machine Learning", "Classification", [
    q("Which metric is most useful when false negatives are very costly (e.g. disease detection)?",
      ["Accuracy","Precision","Recall","F1 Score"], "c",
      "Recall = TP/(TP+FN). Maximising recall minimises missed positives — critical in medical diagnosis."),
    q("Logistic regression outputs:",
      ["A class label directly","A probability between 0 and 1","A continuous value","A ranking score"], "b",
      "Logistic regression uses the sigmoid function to map any input to a probability between 0 and 1."),
    q("AUC-ROC close to 0.5 means:",
      ["Perfect classifier","Good classifier","Model performs no better than random guessing","Perfect negative classifier"], "c",
      "AUC=0.5 means the ROC curve follows the diagonal — equivalent to random guessing."),
    q("Which algorithm is most interpretable for classification?",
      ["Random Forest","Decision Tree","SVM","Neural Network"], "b",
      "A decision tree can be visualised and its decisions traced — making it the most interpretable option."),
    q("When classes are highly imbalanced, accuracy is misleading because:",
      ["It ignores the feature values","A model predicting only the majority class can score very high","It doesn't account for training time","It requires scaled features"], "b",
      "With 95% negative class: a model that always predicts negative gets 95% accuracy without learning anything useful."),
    q("Precision is defined as:",
      ["TP / (TP + FN)","TP / (TP + FP)","TN / (TN + FP)","FP / (FP + TN)"], "b",
      "Precision = TP/(TP+FP). It measures: of all positive predictions, how many were actually correct?"),
    q("One-vs-Rest (OvR) is a strategy for:",
      ["Binary classification","Feature selection","Multi-class classification using binary classifiers","Ensemble methods"], "c",
      "OvR trains one binary classifier per class (vs. all others), enabling multi-class classification."),
    q("K-Nearest Neighbours classification predicts based on:",
      ["A learned linear boundary","The majority class among the K nearest training points","A probabilistic model","A tree of yes/no decisions"], "b",
      "KNN is instance-based — it finds the K closest training examples and returns their majority class."),
    q("Cross-entropy loss is commonly used for:",
      ["Regression","Clustering","Multi-class classification","Anomaly detection"], "c",
      "Cross-entropy measures the divergence between predicted probabilities and true class labels."),
    q("The confusion matrix diagonal represents:",
      ["False positives","False negatives","Correctly classified samples (TP and TN)","Total samples"], "c",
      "The main diagonal of a confusion matrix holds correctly classified counts for each class."),
])

save("ml-tree-based-learning", "Machine Learning", "Tree-Based Learning", [
    q("What is 'information gain' in a decision tree?",
      ["The depth of the tree","The reduction in entropy after a split","The number of features used","The regularisation strength"], "b",
      "Information gain = entropy before split − weighted entropy after split. Higher gain = better split."),
    q("Pruning a decision tree helps to:",
      ["Speed up training","Reduce overfitting by removing low-value branches","Add more features","Increase tree depth"], "b",
      "Without pruning, trees memorise training data. Pruning removes branches that provide little predictive power."),
    q("Random Forest reduces variance compared to a single tree by:",
      ["Using deeper trees","Using only the best features","Averaging predictions across many decorrelated trees","Training on the full dataset each time"], "c",
      "Each tree sees a random feature subset, reducing correlation. Averaging their predictions lowers variance."),
    q("The 'max_features' parameter in Random Forest controls:",
      ["Maximum tree depth","Number of trees","Number of features considered at each split","Minimum samples per leaf"], "c",
      "Reducing max_features increases tree diversity, which generally improves the ensemble's generalisation."),
    q("Gini impurity measures:",
      ["Tree depth","The probability of misclassifying a randomly chosen sample","The number of features","Regularisation strength"], "b",
      "Gini = 1 - Σ(pᵢ²). A pure node (one class) has Gini=0. Used as an alternative to entropy for splitting."),
    q("What does 'bagging' mean in Random Forest?",
      ["Removing outliers","Training each tree on a random bootstrap sample of the data","Selecting the best features","Pruning weak trees"], "b",
      "Bootstrap Aggregating (Bagging) trains each tree on a different random sample with replacement."),
    q("A very deep decision tree with no pruning is likely to:",
      ["Underfit the training data","Overfit — memorise training data but generalise poorly","Have high bias","Have high regularisation"], "b",
      "Deep trees partition the training space very finely, capturing noise rather than signal."),
    q("Extra Trees differ from Random Forest primarily because:",
      ["They use boosting instead of bagging","Splits are chosen randomly rather than optimally at each node","They use fewer trees","They require feature scaling"], "b",
      "Extra Trees (Extremely Randomised Trees) add another layer of randomness by choosing split thresholds randomly."),
    q("Feature importance in Random Forest is typically measured by:",
      ["Correlation coefficient","How much each feature reduces impurity across all trees","Lasso coefficient magnitude","P-values from t-tests"], "b",
      "Mean Decrease in Impurity sums each feature's contribution to reducing Gini/entropy across all splits in all trees."),
    q("When would you prefer a single decision tree over a Random Forest?",
      ["When you need the highest accuracy","When interpretability and explainability are the primary requirement","When training speed is not important","When data is large"], "b",
      "A single tree can be visualised and explained to stakeholders; a forest of 500 trees cannot be easily interpreted."),
])

save("ml-boosting", "Machine Learning", "Boosting", [
    q("In gradient boosting, each new tree is trained to:",
      ["Replicate the previous tree","Correct the errors (residuals) of the previous ensemble","Randomly sample features","Reduce training data size"], "b",
      "Each tree fits the negative gradient of the loss — effectively the residuals from the current ensemble."),
    q("A lower learning_rate in gradient boosting means:",
      ["Faster training","More trees needed but usually better generalisation","Higher variance","Less regularisation"], "b",
      "Lower learning rate shrinks each tree's contribution, requiring more trees to converge but reducing overfitting risk."),
    q("XGBoost improved over classic GBM primarily by adding:",
      ["Regularisation (L1/L2) and system optimisations","Deeper trees","More estimators by default","GPU support only"], "a",
      "XGBoost adds column subsampling, row subsampling, L1/L2 regularisation, and tree pruning — improvements over sklearn GBM."),
    q("Early stopping in XGBoost stops training when:",
      ["All features have been used","Validation score stops improving for N consecutive rounds","Training loss reaches zero","Memory limit is reached"], "b",
      "Early stopping monitors a validation metric. If it doesn't improve for `early_stopping_rounds`, training stops to prevent overfitting."),
    q("LightGBM's 'leaf-wise' tree growth differs from 'level-wise' by:",
      ["Growing the entire level before moving deeper","Always splitting the leaf with the highest loss reduction regardless of depth","Using fewer features","Requiring more memory"], "b",
      "Leaf-wise growth can create deeper trees faster and achieve lower loss, but can overfit on small datasets without constraints."),
    q("The 'subsample' parameter in XGBoost controls:",
      ["Fraction of features used per tree","Fraction of training rows sampled per tree","L2 regularisation strength","Number of parallel threads"], "b",
      "subsample < 1.0 means each tree is trained on a random fraction of rows — reducing variance and adding diversity."),
    q("CatBoost is specifically designed to handle:",
      ["Missing values","Categorical features natively without label encoding","GPU training only","Very small datasets"], "b",
      "CatBoost implements ordered target statistics to handle categorical features without leakage — a common issue with simple label encoding."),
    q("Which metric should you optimise for imbalanced binary classification in boosting?",
      ["Accuracy","AUC-ROC","RMSE","Gini impurity"], "b",
      "AUC-ROC is threshold-independent and robust to class imbalance. Accuracy is misleading when classes are skewed."),
    q("The 'n_estimators' parameter controls:",
      ["Maximum tree depth","Number of boosting rounds (trees)","Learning rate decay","Feature sampling fraction"], "b",
      "Each 'estimator' in boosting is one sequential tree. More estimators = longer training but potentially better fit."),
    q("To prevent overfitting in XGBoost, you should NOT:",
      ["Use early stopping","Increase max_depth without limit","Reduce learning_rate","Use column subsampling"], "b",
      "Increasing max_depth makes trees more complex and more likely to overfit. Keeping it in range 3–8 is typical."),
])

save("ml-svm", "Machine Learning", "Support Vector Machines", [
    q("The support vectors are:",
      ["All training data points","The closest data points to the decision boundary","The misclassified points","Feature weights"], "b",
      "Support vectors are the training examples that lie on or closest to the margin boundary. Only they determine the hyperplane."),
    q("The 'margin' in SVM refers to:",
      ["The model's accuracy","The distance between the decision boundary and the nearest support vectors","The regularisation penalty","The number of features"], "b",
      "SVM maximises this margin — the wider it is, the better the generalisation to new data."),
    q("The RBF (Radial Basis Function) kernel is used when:",
      ["Data is linearly separable","Data requires non-linear decision boundaries","You have very large datasets","Features are all categorical"], "b",
      "RBF maps data to infinite dimensions implicitly using the kernel trick, enabling non-linear boundaries."),
    q("The C parameter in SVM controls:",
      ["Number of support vectors","Trade-off between margin size and misclassification penalty","Kernel bandwidth","Learning rate"], "a",
      "High C = smaller margin, fewer misclassifications (risk of overfitting). Low C = wider margin, more tolerance for errors."),
    q("SVM is NOT recommended when:",
      ["Data is linearly separable","You need maximum-margin classification","The dataset has millions of rows","Features are already scaled"], "c",
      "SVM training scales quadratically with data size. For millions of rows, tree-based methods or neural nets are far more efficient."),
    q("The kernel trick in SVM allows:",
      ["Faster gradient descent","Computing similarity in a higher-dimensional space without explicitly mapping there","Automatic feature selection","Handling missing values"], "b",
      "The kernel computes dot products in the transformed space implicitly — avoiding the computational cost of explicit transformation."),
    q("SVR (Support Vector Regression) uses an 'epsilon tube' to:",
      ["Regularise the model","Ignore errors smaller than epsilon — only support vectors outside the tube matter","Remove outliers","Scale features automatically"], "b",
      "Data points within the epsilon tube contribute zero loss. Only points outside it become support vectors and influence the fit."),
    q("If you have a 3-class problem, OvO (One-vs-One) SVM trains:",
      ["3 classifiers","6 classifiers","9 classifiers","1 classifier"], "b",
      "OvO trains C(n,2) = n*(n-1)/2 classifiers. For 3 classes: 3*2/2 = 3 classifiers."),
    q("Feature scaling is mandatory for SVM because:",
      ["SVM requires integer inputs","The kernel distance is sensitive to feature magnitudes — unscaled features dominate","SVM cannot handle negative values","The algorithm uses log-loss"], "b",
      "Without scaling, features with large ranges dominate the distance metric, skewing the decision boundary."),
    q("Which SVM kernel is equivalent to applying polynomial regression?",
      ["Linear kernel","RBF kernel","Polynomial kernel","Sigmoid kernel"], "c",
      "The polynomial kernel K(x,z) = (x·z + c)^d computes dot products in polynomial feature space."),
])

save("ml-clustering", "Machine Learning", "Clustering", [
    q("Silhouette score near +1 means:",
      ["Clusters are overlapping","Data points are well-matched to their cluster, far from others","Wrong number of clusters","The model has overfit"], "b",
      "Silhouette = (b - a) / max(a,b) where a = intra-cluster distance, b = nearest-cluster distance. Near 1 = tight, well-separated clusters."),
    q("DBSCAN requires you to specify:",
      ["Number of clusters K","Initial cluster centroids","Epsilon (neighbourhood radius) and min_samples","Maximum number of iterations"], "c",
      "DBSCAN defines clusters as dense regions separated by low-density areas. Epsilon and min_samples define 'dense'."),
    q("K-Means assumes clusters are:",
      ["Arbitrarily shaped","Spherical and of similar size","Linearly separable","Hierarchically nested"], "b",
      "K-Means minimises Euclidean distance to centroids, which implicitly assumes spherical, equally-sized clusters."),
    q("The elbow method helps choose:",
      ["The optimal number of clusters K","The distance metric","Epsilon for DBSCAN","Number of outliers"], "a",
      "Plot inertia vs K. The 'elbow' — where inertia reduction slows sharply — suggests the optimal K."),
    q("DBSCAN can discover clusters of:",
      ["Only spherical shape","Fixed size only","Arbitrary shape, and labels low-density points as noise","Exactly K clusters always"], "c",
      "DBSCAN is density-based and makes no shape assumptions. Points in sparse regions are labelled -1 (noise/outlier)."),
    q("What are 'core points' in DBSCAN?",
      ["Points on the cluster boundary","Points with at least min_samples neighbours within epsilon","The cluster centroids","The outlier points"], "b",
      "A core point has ≥ min_samples neighbours within its epsilon neighbourhood. It forms the dense core of a cluster."),
    q("Hierarchical clustering produces:",
      ["A fixed K clusters","A dendrogram showing merges/splits at all distances","A single centroid","Binary decision trees"], "b",
      "Hierarchical clustering builds a tree of merges (agglomerative) or splits (divisive). You choose the cut level to get K clusters."),
    q("When K-Means is run multiple times with 'n_init > 1', it:",
      ["Uses different datasets each time","Runs with different random initialisations and picks the best result","Changes K each time","Applies regularisation"], "b",
      "Different random starting centroids can converge to different local minima. Multiple initialisations help find the global optimum."),
    q("Cluster inertia measures:",
      ["Distance between cluster centres","Sum of squared distances from each point to its cluster centroid","Number of outliers","Model accuracy"], "b",
      "Inertia = Σ min distance² to assigned centroid. Lower inertia means tighter, more compact clusters."),
    q("Gaussian Mixture Models (GMM) differ from K-Means by:",
      ["Using fewer clusters","Assigning soft probabilities of cluster membership instead of hard assignments","Requiring feature scaling","Using L1 distance"], "b",
      "GMM is a probabilistic model — each point has a probability distribution over clusters rather than a hard assignment."),
])

# For brevity, creating summary quiz files for remaining ML topics
save("ml-anomaly-detection", "Machine Learning", "Anomaly Detection", [
    q("Isolation Forest labels -1 for:", ["Normal points","Anomalies","Borderline cases","Duplicate rows"], "b",
      "IsolationForest.predict() returns -1 for anomalies and 1 for normal points."),
    q("Z-score outlier detection typically flags points beyond:", ["±1 SD","±2 SD","±3 SD","±5 SD"], "c",
      "3 standard deviations captures 99.7% of normally distributed data. Points beyond are flagged as outliers."),
    q("LOF detects anomalies by comparing:", ["Distance to centroid","Local density to that of k nearest neighbours","Z-score","Reconstruction error"], "b",
      "LOF measures how isolated a point is relative to its local neighbourhood density."),
    q("The main challenge with real-world anomaly detection is:", ["Too many features","Missing labels","Extreme class imbalance (anomalies are rare)","Data is always structured"], "c",
      "In fraud or fault detection, anomalies may be <1% of data, making standard accuracy metrics meaningless."),
    q("An Autoencoder detects anomalies because:", ["High reconstruction error indicates the model cannot recreate unusual inputs","Low reconstruction error","Zero latent representation","Perfect output match"], "a",
      "Autoencoders trained on normal data struggle to reconstruct anomalies, resulting in high reconstruction error."),
    q("The 'contamination' parameter in IsolationForest sets:", ["Tree depth","The expected fraction of anomalies in the dataset","Number of trees","Random seed"], "b",
      "contamination tells the algorithm what fraction of samples to label as anomalies when calling predict()."),
    q("One-Class SVM is useful when:", ["Both normal and anomaly labels are available","Only normal data is available during training","Data has many features","Speed is critical"], "b",
      "One-Class SVM learns a boundary around normal data without any anomaly examples."),
    q("ROC-AUC is preferred for anomaly detection evaluation because:", ["It is fast to compute","It is threshold-independent and works well with imbalanced classes","It measures absolute error","It requires no labels"], "b",
      "ROC-AUC summarises performance across all classification thresholds, important when the optimal threshold is unknown."),
    q("DBSCAN can be used for anomaly detection because:", ["It removes outliers by default","Points in sparse regions are labelled as noise (-1)","It always finds the right number of clusters","It scales to large datasets"], "b",
      "DBSCAN's noise points (label -1) are naturally isolated from dense clusters — effectively anomaly candidates."),
    q("Which metric should NOT be used as the only metric for imbalanced anomaly detection?", ["Precision","Recall","F1 Score","Raw accuracy"], "d",
      "With 99% normal data, a model that always predicts 'normal' gets 99% accuracy — completely useless."),
])

save("ml-naive-bayes-lda", "Machine Learning", "Naive Bayes / LDA", [
    q("The 'Naive' in Naive Bayes means:", ["Simple to implement","Uses few parameters","Features are assumed conditionally independent given the class","Only works on small data"], "c",
      "Naive Bayes assumes P(x1,x2|y) = P(x1|y) * P(x2|y). This independence assumption is often violated but the model still works well in practice."),
    q("MultinomialNB is best for:", ["Continuous numeric features","Text classification with word frequency counts","Binary yes/no features","Image pixels"], "b",
      "MultinomialNB models word count distributions, making it ideal for document classification tasks."),
    q("LDA serves dual purposes as:", ["Clustering and regression","Anomaly detection and feature selection","Classifier and supervised dimensionality reduction","Boosting and bagging"], "c",
      "LDA finds directions that maximise class separation, both for classification and projecting to lower dimensions."),
    q("Laplace smoothing prevents:", ["Overfitting on large datasets","Zero-probability for unseen features","Multicollinearity","Class imbalance"], "b",
      "Without smoothing, a word unseen in training gives probability 0, zeroing out the entire posterior. Laplace adds a small constant."),
    q("GaussianNB assumes features follow:", ["Uniform distribution","Binomial distribution","Gaussian (normal) distribution","Poisson distribution"], "c",
      "GaussianNB models continuous features as normally distributed within each class."),
    q("LDA assumes:", ["Non-linear class boundaries","All classes share the same covariance matrix","Features are independent","No distributional assumptions"], "b",
      "LDA (Fisher's) assumes equal class covariance. When this is violated, QDA (Quadratic DA) is preferred."),
    q("Naive Bayes works well with text because:", ["Text features are always independent","Word counts are large sparse vectors where the independence assumption is practically useful","Text has no missing values","Word order matters"], "b",
      "Despite the false independence assumption, NB handles high-dimensional sparse text features efficiently and generalises well."),
    q("BernoulliNB is most appropriate when:", ["Features are word counts","Features are binary (word present/absent)","Features are continuous","Classes are imbalanced"], "b",
      "BernoulliNB models binary features — suitable for bag-of-words where you only care whether a word appears, not how often."),
    q("Compared to logistic regression, Naive Bayes is generally:", ["Slower to train","More accurate on large data","Faster to train but less accurate when independence assumption is violated","Better at handling correlated features"], "c",
      "NB is very fast and effective when features are roughly independent. LR usually outperforms NB when features are correlated."),
    q("QDA (Quadratic DA) differs from LDA by:", ["Using fewer features","Allowing each class to have its own covariance matrix","Being faster to train","Requiring fewer samples"], "b",
      "QDA relaxes LDA's equal-covariance assumption, allowing quadratic boundaries — more flexible but needs more data."),
])

save("ml-time-series", "Machine Learning", "Time Series Forecasting", [
    q("ARIMA requires the input series to be:", ["Seasonal","Stationary","Normalized","Log-transformed"], "b",
      "ARIMA (AutoRegressive Integrated Moving Average) requires stationarity. The 'I' (integrated) component handles differencing to achieve it."),
    q("MAPE measures:", ["Mean Absolute Percentage Error","Mean Absolute Prediction Error","Model Accuracy Per Epoch","Maximum Absolute Prediction Error"], "a",
      "MAPE = mean(|actual - predicted| / |actual|) * 100. A scale-free metric good for comparing across datasets."),
    q("In ARIMA(p, d, q), 'd' represents:", ["Number of autoregressive terms","Degree of differencing","Number of moving average terms","Seasonal period"], "b",
      "'d' is the order of differencing needed to make the series stationary. d=1 means first differencing."),
    q("Prophet was designed for:", ["Stock price prediction","Real-time sensor data","Business time series with holidays and multiple seasonalities","High-frequency financial data"], "c",
      "Meta's Prophet handles daily/weekly/yearly seasonality and holiday effects automatically with minimal configuration."),
    q("The Augmented Dickey-Fuller (ADF) test checks for:", ["Autocorrelation in residuals","Stationarity of a time series","Seasonality","Forecast accuracy"], "b",
      "Low ADF p-value (< 0.05) rejects the unit root hypothesis — indicating stationarity."),
    q("ACF (Autocorrelation Function) plots help determine:", ["Trend direction","The lag at which correlation drops to near-zero — guiding MA terms","Feature importance","Outliers"], "b",
      "ACF shows correlation at each lag. It helps choose the 'q' (MA order) in ARIMA — q is where ACF cuts off."),
    q("LSTM networks are preferred for time series when:", ["The series is stationary","Complex non-linear long-range dependencies exist","Fewer than 100 data points are available","Speed is critical"], "b",
      "LSTMs can learn long-range dependencies through gated memory cells — useful for complex sequential patterns OLS/ARIMA cannot capture."),
    q("Cross-validation for time series differs from standard k-fold because:", ["It uses more folds","It must preserve temporal order — future data cannot train a model evaluated on past data","It requires scaling","It uses bootstrap sampling"], "b",
      "Time series CV uses expanding or rolling windows, always training on past data and validating on future data."),
    q("Seasonal differencing removes:", ["Trend from the series","The seasonal pattern at lag s (e.g., 12 for monthly)","Random noise","All autocorrelation"], "b",
      "Seasonal differencing: y(t) - y(t-s) removes the periodic component, useful before fitting SARIMA."),
    q("XGBoost with lag features can be used for time series by:", ["Treating it as a sequence prediction problem using RNNs","Converting the series to a supervised problem using lagged values as features","Using the raw series as target","Applying it directly without feature engineering"], "b",
      "Creating features lag_1, lag_2 … lag_n from the series allows standard ML models to treat forecasting as regression."),
])

save("ml-hyperparameter-optimization", "Machine Learning", "Hyperparameter Optimization", [
    q("Which approach is most efficient for expensive-to-train models?",
      ["Grid Search","Random Search","Bayesian Optimization (Optuna/Hyperopt)","Manual trial and error"], "c",
      "Bayesian optimization builds a probabilistic model of the objective, focusing evaluations on promising regions."),
    q("Cross-validation during hyperparameter search helps:",
      ["Reduce training time","Avoid overfitting to a single validation split","Increase model complexity","Remove outliers"], "b",
      "Each configuration is evaluated on multiple folds, giving a more reliable estimate of generalisation performance."),
    q("In k-fold cross-validation:", ["Data is shuffled k times","Each fold serves as test set exactly once while others train","Data is duplicated k times","Hyperparameters change each fold"], "b",
      "K-fold creates k equal-sized folds. Each fold is the test set once; the model is trained on the remaining k-1 folds."),
    q("Using the same test set repeatedly during hyperparameter search causes:", ["Underfitting","Faster convergence","High bias","Data leakage into the tuning process"], "d",
      "The search algorithm can overfit to the test set, selecting hyperparameters that happen to work well on that specific set but not in general."),
    q("sklearn Pipeline ensures:", ["Faster grid search","Scaler/preprocessor fits only on training folds — preventing leakage","Automatic feature selection","Model re-training on each trial"], "b",
      "Without Pipeline, scaling on all data before CV leaks test statistics into training. Pipeline fixes this automatically."),
    q("Nested cross-validation is used to:", ["Speed up hyperparameter search","Get an unbiased estimate of the model's generalisation performance after tuning","Select the best model","Reduce dataset size"], "b",
      "Nested CV has an outer loop for evaluation and inner loop for tuning — keeping the outer test set truly unseen."),
    q("Optuna's suggest_float('lr', 1e-4, 1e-1, log=True) samples from:",
      ["A uniform distribution","A log-uniform distribution — concentrating samples at smaller values","A normal distribution","A fixed set of values"], "b",
      "log=True samples multiplicatively (like 1e-4, 3e-4, 1e-3 ...) rather than linearly, appropriate for learning rates spanning decades."),
    q("Random Search outperforms Grid Search when:", ["All hyperparameters are important","Only a few hyperparameters matter — random search focuses budget on those","The search space is tiny","Training time is unlimited"], "b",
      "If only 2 of 10 hyperparameters matter, grid search wastes evaluations on irrelevant combinations. Random search explores the important dimensions more effectively."),
    q("Halving strategies (Successive Halving) work by:", ["Doubling the dataset each round","Eliminating the worst-performing configurations each round, allocating more budget to survivors","Using gradient descent on hyperparameters","Random elimination"], "b",
      "Successive Halving quickly discards poor configurations, spending compute only on promising ones."),
    q("The 'warm start' parameter in sklearn estimators allows:", ["Using previous training for initialization, speeding up retraining","Skipping cross-validation","Reducing regularisation","Changing the training objective"], "a",
      "warm_start=True reuses the fitted model from the previous call as initialization, useful when incrementally adding estimators."),
])

# Programming quizzes
save("programming-python-basics", "Programming", "Python Basics", [
    q("What does range(2, 10, 3) produce?",
      ["[2,5,8,11]","[2,5,8]","[2,4,6,8]","[2,5,8,10]"], "b",
      "range(start, stop, step) produces 2, 5, 8 — stopping before 10."),
    q("What is the output of [x*2 for x in range(3)]?",
      ["[0,1,2]","[2,4,6]","[0,2,4]","[1,2,3]"], "c",
      "range(3) gives 0,1,2. Multiplied by 2: [0,2,4]."),
    q("Which is used for context management (auto-closing files)?",
      ["try/except","with statement","if/else","for loop"], "a",
      "The 'with' statement invokes __enter__ and __exit__, ensuring resources are released even if an error occurs."),
    q("What is the key difference between a list and a tuple?",
      ["Lists are ordered, tuples are not","Tuples are immutable, lists are mutable","Tuples support indexing, lists do not","Lists can store mixed types, tuples cannot"], "b",
      "Tuples cannot be modified after creation (immutable). Lists support append, remove, etc."),
    q("Which block catches exceptions in Python?",
      ["catch","rescue","except","handle"], "c",
      "Python uses try/except. Java/C++ use try/catch — Python's keyword is 'except'."),
    q("What does *args in a function definition do?",
      ["Passes keyword arguments","Collects extra positional arguments into a tuple","Returns multiple values","Marks the function as async"], "b",
      "*args collects any number of positional arguments beyond the defined parameters into a tuple."),
    q("Dictionary comprehension syntax in Python is:",
      ["{k: v for k, v in items}","[k:v for k,v in items]","(k:v for k in items)","dict(k=v for k,v in items)"], "a",
      "{key: value for item in iterable} creates a dict from an iteration."),
    q("Which built-in function returns the memory address of an object?",
      ["addr()","memory()","id()","ref()"], "c",
      "id() returns the identity of an object — its memory address in CPython."),
    q("'else' in a for loop executes when:",
      ["The loop body raises an exception","The loop completes without hitting a 'break'","Always after the loop","Only if the loop ran zero iterations"], "b",
      "The for-else construct: the else block runs only if the loop wasn't exited via break."),
    q("A generator function uses which keyword?",
      ["return","async","yield","defer"], "c",
      "yield pauses the function and returns a value. On next call, execution resumes from where it left off — memory-efficient for large sequences."),
])

save("programming-python-for-data", "Programming", "Python for Data (Pandas / NumPy)", [
    q("df.groupby('branch')['cgpa'].mean() returns:",
      ["A list of cgpa values","The mean cgpa per branch as a Series","A single number","A boolean mask"], "b",
      "groupby splits the DataFrame by branch, then .mean() computes the mean cgpa within each group, returning a Series indexed by branch."),
    q("np.array.mean(axis=0) computes means along:",
      ["Rows (column-wise means)","Columns (row-wise means)","All elements","The diagonal"], "a",
      "axis=0 collapses rows, computing the mean of each column. axis=1 collapses columns (row-wise means)."),
    q("pd.read_csv('file.csv') loads:",
      ["A numpy array","A Python list","A pandas DataFrame","A dictionary"], "c",
      "read_csv returns a DataFrame — a 2D labelled data structure with rows and named columns."),
    q("df.dropna() removes rows where:",
      ["All values are zero","Column names are missing","Any value is NaN","Duplicate rows exist"], "c",
      "dropna() by default removes rows with at least one NaN. Use dropna(how='all') to only drop fully null rows."),
    q("Which matplotlib function creates a bar chart?",
      ["plt.hist()","plt.bar()","plt.scatter()","plt.pie()"], "b",
      "plt.bar(x, height) creates a vertical bar chart. plt.barh() creates horizontal bars."),
    q("df.merge(other, on='id') performs:",
      ["Concatenation along rows","A SQL-style join on the 'id' column","An outer join only","Element-wise addition"], "b",
      "DataFrame.merge() is pandas' SQL-JOIN equivalent. Default is inner join; use how='left/right/outer' for others."),
    q("np.where(condition, x, y) returns:",
      ["Indices where condition is True","x where condition is True, y where False","A boolean array","The count of True values"], "b",
      "np.where is a vectorised if/else: np.where(arr > 0, arr, 0) replaces negatives with 0."),
    q("df.pivot_table(values='sales', index='region', aggfunc='sum') creates:",
      ["A grouped bar chart","A cross-tabulation with sum of sales per region","A new column","A sorted DataFrame"], "b",
      "pivot_table reshapes data — here it sums 'sales' grouped by 'region', equivalent to a SQL GROUP BY."),
    q("Broadcasting in NumPy allows:",
      ["Looping over arrays automatically","Operations between arrays of different shapes by expanding dimensions","Parallel computation","GPU acceleration"], "b",
      "np.array([1,2,3]) + 10 adds 10 to each element because the scalar is broadcast to match the array's shape."),
    q("df['col'].value_counts() returns:",
      ["Sorted unique values","Frequency of each unique value in the column, sorted descending","The cumulative sum","A boolean mask"], "b",
      "value_counts() is a quick way to see the distribution of categorical data — count of each unique value."),
])

save("programming-shell-bash", "Programming", "Shell / Bash", [
    q("grep -r 'import' src/ does:",
      ["Replaces 'import' in all files","Recursively searches all files under src/ for lines containing 'import'","Counts lines containing 'import'","Removes lines with 'import'"], "b",
      "-r = recursive. grep searches file contents and prints matching lines with filenames."),
    q("The pipe character | in Bash:",
      ["Runs commands in parallel","Passes stdout of the left command as stdin of the right command","Redirects output to a file","Terminates a command"], "b",
      "Piping: `cmd1 | cmd2` sends cmd1's output directly to cmd2's input without creating a temp file."),
    q("chmod +x script.sh does:",
      ["Makes the file executable","Compresses the file","Changes the file owner","Deletes execute permissions"], "a",
      "+x adds execute permission. Without it, you'll get 'Permission denied' when trying to run the script."),
    q("To redirect both stdout and stderr to a file:",
      ["cmd > file","cmd >> file","cmd 2> file","cmd &> file"], "d",
      "&> redirects both file descriptors. Equivalent to cmd > file 2>&1 in older syntax."),
    q("$1 in a bash script refers to:",
      ["The script's process ID","The first command-line argument passed to the script","The last exit code","The script filename"], "b",
      "$0=script name, $1=first arg, $2=second arg, $@=all args as separate words."),
    q("What does 'set -e' do at the top of a script?",
      ["Sets environment variables","Exits the script immediately if any command returns a non-zero exit code","Enables debug mode","Silences all output"], "b",
      "set -e is a safety mechanism — your script won't silently continue after a failed command."),
    q("find . -name '*.py' -type f locates:",
      ["Python processes","All .py files (regular files only) in the current directory tree","All directories named .py","Files modified today"], "b",
      "-type f restricts to regular files. -name uses glob patterns. '.' starts from the current directory."),
    q("'&&' between two commands means:",
      ["Run both commands in parallel","Run the second command only if the first succeeds","Always run both","Run the second command only if the first fails"], "b",
      "cmd1 && cmd2: cmd2 runs only if cmd1 exits with status 0 (success)."),
    q("The difference between > and >> for redirection is:",
      ["No difference",">> appends to the file; > overwrites it","> creates a new file only",">> is faster"], "b",
      "> truncates and overwrites. >> appends. Use >> when you want to add to existing content."),
    q("What does $? contain?",
      ["Current user's home directory","The last command's exit code (0=success, non-zero=error)","All environment variables","The script's arguments"], "b",
      "$? is tested after commands to check if they succeeded. Common in if [ $? -eq 0 ]; then ... patterns."),
])

save("programming-sql", "Programming", "SQL", [
    q("Which clause filters results AFTER grouping?",
      ["WHERE","HAVING","FILTER","GROUP FILTER"], "b",
      "WHERE filters rows before aggregation. HAVING filters groups after GROUP BY aggregation."),
    q("LEFT JOIN returns:",
      ["Only matching rows from both tables","All rows from the left table, NULLs where no match in right","All rows from both tables","Only rows with no match"], "b",
      "LEFT JOIN ensures all left-table rows appear in results, with NULLs for right-table columns when unmatched."),
    q("RANK() vs ROW_NUMBER(): the key difference is:",
      ["RANK is faster","RANK assigns the same rank to ties and skips the next value(s); ROW_NUMBER always gives unique sequential numbers","ROW_NUMBER works only with ORDER BY","RANK requires a PARTITION BY"], "c",
      "Ties: RANK gives 1,1,3 (skips 2); DENSE_RANK gives 1,1,2; ROW_NUMBER gives 1,2,3."),
    q("COALESCE(col1, col2, 'default') returns:",
      ["Sum of non-null values","Always col1","The first non-null value in the list","NULL if any input is null"], "c",
      "COALESCE evaluates arguments left to right and returns the first non-null value — useful for fallback values."),
    q("A window function (e.g. SUM OVER) differs from GROUP BY because:",
      ["It computes aggregates without collapsing rows","It is faster","It only works with COUNT","It requires a subquery"], "a",
      "Window functions compute values across a window of rows while preserving each row's detail — GROUP BY collapses rows."),
    q("What does DISTINCT do in SELECT?",
      ["Sorts results","Removes duplicate rows from the result set","Selects a random sample","Speeds up the query"], "b",
      "SELECT DISTINCT col returns unique values only — identical to SELECT col but with duplicates removed."),
    q("An index in a SQL table:",
      ["Stores duplicate data","Speeds up data retrieval at the cost of insert/update performance","Enforces uniqueness always","Replaces the primary key"], "b",
      "Indexes are data structures (usually B-trees) that allow fast lookups. Trade-off: faster reads, slower writes."),
    q("INNER JOIN returns:",
      ["All rows from both tables","Only rows that have matching values in both tables","All rows from the left table","All rows from the right table"], "b",
      "INNER JOIN is the most restrictive join — only rows with matches in both tables appear in results."),
    q("CTE (Common Table Expression) is defined using:",
      ["CREATE TEMP TABLE","WITH name AS (SELECT ...)","DECLARE @name AS","SUBQUERY()"], "b",
      "WITH cte AS (SELECT ...) SELECT * FROM cte. CTEs improve readability and allow recursive queries."),
    q("What does NULLIF(a, b) return?",
      ["NULL if a is null","NULL if a equals b, otherwise a","b if a is null","Always NULL"], "b",
      "NULLIF(a,b) returns NULL if a=b, otherwise returns a. Useful to avoid division by zero: col / NULLIF(denominator, 0)."),
])

print("\nAll quiz JSON files generated.")
print(f"Total files: {len(os.listdir('data/quizzes'))}")
